### PR TITLE
Fixes #268 + #263 + #278 + #279

### LINKED ISSUE #268: AWS codeploy validate.sh improvement
The generated validate.sh file waits a fixed time (it can be changed - parameter on pom.xml) to validate if the service started. I think it can be improved:

**Current appspec.yml**
validate service step timeout: 3600 seconds

**Current validate.sh**
sleep [fixed time|default 10 seconds]
if [service if not up]{
   raise error
}

**Desired appspec.yml**
validate service step timeout: [fixed time|default 10 seconds]

**Desired validate.sh**
while [service is not UP]{
    sleep 1 second
}

### PR DESCRIPTION
**Pull request by roneigebert**

### CODE REVIEW

**Comment by roneigebert** [comment]
@miere for your review ;)

**Comment by miere** [comment]
Hey @roneigebert . How is everything?

I'm reaching out to check if this ticket is still required?
If so, let me know so I can merge it.

**Review by miere — DISMISSED** [review]

**Comment by roneigebert** [comment]
Hi @miere! Yes it's still required, at this moment we're using this script on a custom codedeploy package (as a provisional solution)

**Comment by miere** [comment]
Awesome, mate.

I'm finally having time to review this as I finally transitioned to normal hours of work. I spent my last year working mostly on two shifts, couldn't spend quality time here.

**Pull request merged**
